name: Feature request
description: Propose an improvement.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe expected behavior and scope.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Share other options and tradeoffs.

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: List concrete checks to consider this done.
      placeholder: |
        - [ ] ...
        - [ ] ...
